osx_image: xcode9
language: objective-c
sudo: required
env:
  global:
    - PROJECT="ReactorKit.xcodeproj"
    - SCHEME="ReactorKit-Package"
    - IOS_SDK="iphonesimulator11.0"
    - MACOS_SDK="macosx10.13"
    - TVOS_SDK="appletvsimulator11.0"
    - FRAMEWORK="ReactorKit"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"
    - SDK="$MACOS_SDK"    DESTINATION="arch=x86_64"
    - SDK="$TVOS_SDK"     DESTINATION="OS=11.0,name=Apple TV 1080p"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version
  - bundle install

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
      -project "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION"
      -configuration Debug
      -enableCodeCoverage YES
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'ReactorKit';

before_deploy:
  - bundle exec swiftproj generate-xcconfig --podspec ReactorKit.podspec
  - bundle exec swiftproj generate-xcodeproj --xcconfig-overrides Config.xcconfig
  - bundle exec swiftproj configure-scheme --project ReactorKit.xcodeproj --scheme ReactorKit-Package --buildable-targets ReactorKit,ReactorKitRuntime
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKit --framework RxBlocking.framework
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKit --framework RxCocoa.framework
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKit --framework RxCocoaRuntime.framework
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKitRuntime --framework RxBlocking.framework
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKitRuntime --framework RxCocoa.framework
  - bundle exec swiftproj remove-framework --project ReactorKit.xcodeproj --target ReactorKitRuntime --framework RxCocoaRuntime.framework
  - rm -rf Examples  # https://github.com/Carthage/Carthage/issues/1974
  - carthage bootstrap
  - carthage build --no-skip-current --verbose | xcpretty -c
  - carthage archive ReactorKit ReactorKitRuntime

deploy:
  provider: releases
  api_key:
    secure: iQLQ+53ce6rCfnwps+Q2Leq4wgkystcN9wk+3vtnkMFFW/n2myuZQF5lzBkFGI9YUJDwPl+unjT80Fkr6sxHk63DZw6hhqRFf2AlDtO20goa32WRR0MfCnL7CfxWnIywfXN4F9LaJQkghtihmeGng5USzur7CGpfdR9oXQ+JgGLl9HjhXpoRVkDNFBZ72AL+/q9ZjV5ZXHjTkaW5yAMsHo21SM8nfiOuCNTtmmybDp9FVeMAHvWCLXakKCLGBG3B6p73UhMQQXlvWARPAhi2ux+VMqcyydUG1DYilkSNAc+a4v8twWx750Lte0hAy/E17ZoxsZhhf0qPrYgUWlgKN7G4qeU95YOSmiWuhOqyZsb3pUyV0uBqaYpUMqK+C0UIRuzv1EOluZ+ysNUqKkQv7ogVyfCPfxhwxSwbpPpM66we7cpFZPz5Tt6r2mqa5CURsLNll3d1kzJNHq96IjfjTRceEkMA6SC2avJe3ASx+vEIlshuldyANVxpZ9aGt64KyuDpZA0Fjh41jSVWT4dAJ0zXXPMHHZLwH3JDq3AK/r5GlRbrIp+yM1r0JSXTxnjKQ8g5NACRrHiW6u/tu4nc/r/r1TLzO5dMHS9TGs4ql6qvmukqODfQxBU9gaGqqa9TVAKSKL12ZNOg9JvT4cpH+HKtwSRmb2PE7k4jGP2Pu1A=
  file: "$FRAMEWORK.framework.zip"
  skip_cleanup: true
  on:
    repo: ReactorKit/ReactorKit
    tags: true
    condition: $SDK = $IOS_SDK
